package com.thinkerscave.finance.dto.request;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class GenerationSettingsRequest {
    @NotNull
    private Boolean autoGenerateDues;
    @NotNull @Min(0)
    private Integer generationLeadDays;
    @NotNull @Min(1) @Max(28)
    private Short defaultDueDayForNewStructures;
}
