-- ============================================
-- DEV Demo Data for H2 Database
-- ThinkersCave SaaS - Education Management Platform
-- ============================================
-- Runs AFTER Hibernate creates entity tables (defer-datasource-initialization=true).
-- Password for all users: "Password@123" (BCrypt encoded below)
-- Audit columns (created_date, last_modified_date, etc.) omitted - they are nullable.
-- ============================================

-- ============================================
-- 0. NON-ENTITY TABLES (not managed by Hibernate)
-- ============================================
CREATE TABLE IF NOT EXISTS user_tenant_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(255),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL UNIQUE,
    tenant_name VARCHAR(255) NOT NULL,
    subdomain VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    features TEXT,
    max_users INT DEFAULT 100,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 1. ORGANISATION
-- ============================================
INSERT INTO organisation (org_id, org_code, org_name, brand_name, org_url, type, city, state, country, zip_code, email, phone_number, website, establishment_date, subscription_type, registration_number, affiliation, tenant_schema, description) VALUES
(1, 'ORG001', 'ThinkersCave Academy', 'ThinkersCave', '/app', 'SCHOOL', 'Bangalore', 'Karnataka', 'India', '560001', 'admin@thinkerscave.com', '9876543210', 'https://thinkerscave.com', '2020-06-15', 'PREMIUM', 'REG-2020-BLR-001', 'CBSE', 'public', 'Premier educational institution'),
(2, 'ORG002', 'ThinkersCave Engineering College', 'TC Engineering', '/app', 'COLLEGE', 'Mumbai', 'Maharashtra', 'India', '400001', 'engineering@thinkerscave.com', '9876543211', 'https://engineering.thinkerscave.com', '2018-08-01', 'ENTERPRISE', 'REG-2018-MUM-002', 'AICTE', 'public', 'Engineering college');

-- ============================================
-- 2. ROLES
-- ============================================
INSERT INTO role_master (role_id, role_name, role_code, description, is_active, role_type, organization_id) VALUES
(1, 'Super Admin', 'SUPER_ADMIN', 'Full system access', TRUE, 'ADMIN', 1),
(2, 'Admin', 'ADMIN', 'Organization administrator', TRUE, 'ADMIN', 1),
(3, 'Teacher', 'TEACHER', 'Teaching staff', TRUE, 'SCHOOL', 1),
(4, 'Student', 'STUDENT', 'Student access', TRUE, 'SCHOOL', 1),
(5, 'Parent', 'PARENT', 'Parent/Guardian access', TRUE, 'SCHOOL', 1),
(6, 'Counsellor', 'COUNSELLOR', 'Admission counsellor', TRUE, 'SCHOOL', 1),
(7, 'Accountant', 'ACCOUNTANT', 'Finance team', TRUE, 'SCHOOL', 1),
(8, 'IT Support', 'IT_SUPPORT', 'Technical support', TRUE, 'ADMIN', 1);

-- ============================================
-- 3. USERS (Password: Password@123)
-- ============================================
INSERT INTO users (id, user_code, first_name, middle_name, last_name, email, mobile_number, user_name, password, address, city, state, country, zip_code, gender, is_blocked, is_2fa_enabled, attempts, is_first_time_login, is_email_verified, is_mobile_verified, date_of_birth, last_login_date) VALUES
(1,  'USR001', 'Rajesh',  NULL, 'Kumar',    'admin@thinkerscave.com',          9876543210, 'superadmin',   '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '100 MG Road',       'Bangalore', 'Karnataka', 'India', '560001', 'Male',   FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1985-03-15', '2026-05-20'),
(2,  'USR002', 'Priya',   NULL, 'Sharma',   'priya.sharma@thinkerscave.com',   9876543211, 'admin',        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '45 Park Street',    'Bangalore', 'Karnataka', 'India', '560002', 'Female', FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1988-07-22', '2026-05-19'),
(3,  'USR003', 'Amit',    'K',  'Verma',    'amit.verma@thinkerscave.com',     9876543212, 'teacher1',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '78 Residency Road', 'Bangalore', 'Karnataka', 'India', '560025', 'Male',   FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1990-11-10', '2026-05-18'),
(4,  'USR004', 'Sunita',  NULL, 'Patel',    'sunita.patel@thinkerscave.com',   9876543213, 'teacher2',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '22 Brigade Road',   'Bangalore', 'Karnataka', 'India', '560001', 'Female', FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1992-04-05', '2026-05-17'),
(5,  'USR005', 'Rahul',   NULL, 'Singh',    'rahul.singh@thinkerscave.com',    9876543214, 'student1',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '56 Koramangala',    'Bangalore', 'Karnataka', 'India', '560034', 'Male',   FALSE, FALSE, 0, FALSE, TRUE, TRUE, '2008-09-12', NULL),
(6,  'USR006', 'Ananya',  NULL, 'Reddy',    'ananya.reddy@thinkerscave.com',   9876543215, 'student2',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '34 Whitefield',     'Bangalore', 'Karnataka', 'India', '560066', 'Female', FALSE, FALSE, 0, FALSE, TRUE, TRUE, '2009-01-25', NULL),
(7,  'USR007', 'Vikram',  NULL, 'Malhotra', 'vikram.malhotra@thinkerscave.com',9876543216, 'student3',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '89 Indiranagar',    'Bangalore', 'Karnataka', 'India', '560038', 'Male',   FALSE, FALSE, 0, FALSE, TRUE, TRUE, '2008-06-18', NULL),
(8,  'USR008', 'Meera',   NULL, 'Nair',     'meera.nair@thinkerscave.com',     9876543217, 'parent1',      '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '56 Koramangala',    'Bangalore', 'Karnataka', 'India', '560034', 'Female', FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1978-12-03', NULL),
(9,  'USR009', 'Deepak',  NULL, 'Joshi',    'deepak.joshi@thinkerscave.com',   9876543218, 'counsellor1',  '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '12 HSR Layout',     'Bangalore', 'Karnataka', 'India', '560102', 'Male',   FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1991-08-14', '2026-05-20'),
(10, 'USR010', 'Kavitha', NULL, 'Menon',    'kavitha.menon@thinkerscave.com',  9876543219, 'accountant1',  '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '67 Jayanagar',      'Bangalore', 'Karnataka', 'India', '560041', 'Female', FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1989-05-30', '2026-05-20');

-- ============================================
-- 4. USER-ROLE MAPPING
-- ============================================
INSERT INTO user_roles (user_id, role_id) VALUES
(1, 1), (2, 2), (3, 3), (4, 3), (5, 4), (6, 4), (7, 4), (8, 5), (9, 6), (10, 7);

-- ============================================
-- 5. ORGANIZATION-USER MAPPING
-- ============================================
INSERT INTO organization_users (id, organization_id, user_id, role_name, is_active, joined_at, updated_at) VALUES
(1, 1, 1, 'SUPER_ADMIN', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 2, 'ADMIN', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 3, 'TEACHER', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 1, 4, 'TEACHER', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 5, 'STUDENT', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 6, 'STUDENT', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 1, 7, 'STUDENT', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 1, 8, 'PARENT', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 1, 9, 'COUNSELLOR', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 1, 10, 'ACCOUNTANT', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================
-- 6. USER-TENANT MAPPING (non-entity table)
-- ============================================
INSERT INTO user_tenant_mapping (email, username, tenant_id, is_active) VALUES
('admin@thinkerscave.com', 'superadmin', 'public', TRUE),
('priya.sharma@thinkerscave.com', 'admin', 'public', TRUE),
('amit.verma@thinkerscave.com', 'teacher1', 'public', TRUE),
('sunita.patel@thinkerscave.com', 'teacher2', 'public', TRUE),
('rahul.singh@thinkerscave.com', 'student1', 'public', TRUE),
('ananya.reddy@thinkerscave.com', 'student2', 'public', TRUE),
('vikram.malhotra@thinkerscave.com', 'student3', 'public', TRUE),
('meera.nair@thinkerscave.com', 'parent1', 'public', TRUE),
('deepak.joshi@thinkerscave.com', 'counsellor1', 'public', TRUE),
('kavitha.menon@thinkerscave.com', 'accountant1', 'public', TRUE);

-- ============================================
-- 7. TENANT CONFIG (non-entity table)
-- ============================================
INSERT INTO tenant_config (tenant_id, tenant_name, subdomain, is_active, features, max_users) VALUES
('public', 'ThinkersCave Academy', 'demo', TRUE, '{"courseLabel":"Course","studentLabel":"Student","staffLabel":"Staff"}', 500);

-- ============================================
-- 8. PRIVILEGES
-- ============================================
INSERT INTO privilege_master (privilege_id, privilege_name) VALUES
(1, 'VIEW'), (2, 'ADD'), (3, 'EDIT'), (4, 'DELETE'), (5, 'APPROVE');

-- ============================================
-- 9. MENUS
-- ============================================
INSERT INTO menu_master (menu_id, menu_code, name, description, url, icon, menu_order, is_active) VALUES
(1, 'MENU_DASHBOARD', 'Dashboard', 'Main dashboard', '/app', 'pi pi-home', 1, TRUE),
(2, 'MENU_STUDENT', 'Student Management', 'Manage students', '/app/managestudent', 'pi pi-users', 2, TRUE),
(3, 'MENU_STAFF', 'Staff Management', 'Manage staff', '/app/staff', 'pi pi-id-card', 3, TRUE),
(4, 'MENU_ACADEMICS', 'Academics', 'Academic management', '/app/academics', 'pi pi-book', 4, TRUE),
(5, 'MENU_ATTENDANCE', 'Attendance', 'Attendance tracking', '/app/attendance', 'pi pi-calendar', 5, TRUE),
(6, 'MENU_INQUIRY', 'Inquiry & Admissions', 'Inquiry management', '/app/inquiry', 'pi pi-phone', 6, TRUE),
(7, 'MENU_FEES', 'Fee Management', 'Fee and payments', '/app/fees', 'pi pi-wallet', 7, TRUE),
(8, 'MENU_ADMIN', 'Administration', 'System admin', '/app/admin', 'pi pi-cog', 8, TRUE),
(9, 'MENU_REPORTS', 'Reports', 'Reports and analytics', '/app/reports', 'pi pi-chart-bar', 9, TRUE);

-- ============================================
-- 10. SUB-MENUS
-- ============================================
INSERT INTO sub_menu_master (sub_menu_id, sub_menu_name, sub_menu_code, sub_menu_description, sub_menu_url, sub_menu_icon, sub_menu_order, is_active, menu_id) VALUES
(1, 'Overview', 'DASHBOARD_OVERVIEW', 'Dashboard overview', '/app', 'pi pi-home', 1, TRUE, 1),
(2, 'Manage Students', 'STUDENT_MANAGE', 'Student CRUD', '/app/managestudent', 'pi pi-users', 1, TRUE, 2),
(3, 'Manage Class', 'STUDENT_CLASS', 'Class management', '/app/manage-class', 'pi pi-th-large', 2, TRUE, 2),
(4, 'Manage Section', 'STUDENT_SECTION', 'Section management', '/app/manage-section', 'pi pi-table', 3, TRUE, 2),
(5, 'Manage Staff', 'STAFF_MANAGE', 'Staff CRUD', '/app/staff', 'pi pi-id-card', 1, TRUE, 3),
(6, 'Departments', 'STAFF_DEPT', 'Department management', '/app/manage-department', 'pi pi-sitemap', 2, TRUE, 3),
(7, 'Branches', 'STAFF_BRANCH', 'Branch management', '/app/manage-branch', 'pi pi-building', 3, TRUE, 3),
(8, 'Salary', 'STAFF_SALARY', 'Payroll management', '/app/salary', 'pi pi-money-bill', 4, TRUE, 3),
(9, 'Leave', 'STAFF_LEAVE', 'Leave management', '/app/leave', 'pi pi-calendar-minus', 5, TRUE, 3),
(10, 'Academic Dashboard', 'ACAD_DASHBOARD', 'Academic workspace overview', '/app/academics/dashboard', 'pi pi-chart-line', 1, TRUE, 4),
(11, 'Academic Years', 'ACAD_YEARS', 'Academic year lifecycle', '/app/academics/years', 'pi pi-calendar-clock', 2, TRUE, 4),
(12, 'Classes & Sections', 'ACAD_CLASSES_SECTIONS', 'Class and section workspace', '/app/academics/classes', 'pi pi-sitemap', 3, TRUE, 4),
(13, 'Subjects', 'ACAD_SUBJECTS', 'Subject workspace', '/app/academics/subjects', 'pi pi-book', 4, TRUE, 4),
(14, 'Curriculum Planner', 'ACAD_CURRICULUM', 'Curriculum planning workspace', '/app/academics/curriculum', 'pi pi-sliders-h', 5, TRUE, 4),
(15, 'Class Attendance', 'ATT_CLASS', 'Student attendance', '/app/attendance/class', 'pi pi-check-square', 1, TRUE, 5),
(16, 'Staff Attendance', 'ATT_STAFF', 'Staff attendance', '/app/attendance/staff', 'pi pi-user-edit', 2, TRUE, 5),
(17, 'Hostel Attendance', 'ATT_HOSTEL', 'Hostel attendance', '/app/attendance/hostel', 'pi pi-building', 3, TRUE, 5),
(18, 'Manage Inquiry', 'INQ_MANAGE', 'Inquiry CRUD', '/app/inquiry/manage', 'pi pi-phone', 1, TRUE, 6),
(19, 'Follow-ups', 'INQ_FOLLOWUP', 'Inquiry follow-ups', '/app/inquiry/followup', 'pi pi-reply', 2, TRUE, 6),
(20, 'Navigation & Access', 'ADMIN_NAV_ACCESS', 'Menu structure, roles, and permissions', '/app/navigation-access', 'pi pi-lock', 1, TRUE, 8),
(21, 'Organization Management', 'ADMIN_ORG', 'Organization settings', '/app/organization-registration', 'pi pi-building', 2, TRUE, 8),
(22, 'System Settings', 'ADMIN_SYSTEM_SETTINGS', 'Workspace preferences and system configuration', '/app/system-settings', 'pi pi-sliders-h', 3, TRUE, 8),
(23, 'Audit & Activity', 'ADMIN_AUDIT_ACTIVITY', 'Administration activity and change history', '/app/audit-activity', 'pi pi-history', 4, TRUE, 8),
(24, 'Role Management', 'ADMIN_ROLE', 'Legacy role management entry retained inactive for migration safety', '/app/role/manage', 'pi pi-shield', 5, FALSE, 8),
(25, 'Role Menu Mapping', 'ADMIN_ROLE_MENU_MAPPING', 'Legacy role-menu mapping entry retained inactive for migration safety', '/app/role-menu-mapping', 'pi pi-lock', 6, FALSE, 8);

INSERT INTO sub_menu_master (sub_menu_id, sub_menu_name, sub_menu_code, sub_menu_description, sub_menu_url, sub_menu_icon, sub_menu_order, is_active, menu_id) VALUES
(26, 'Syllabus Delivery', 'ACAD_SYLLABUS', 'Syllabus planning and delivery tracking', '/app/academics/syllabus', 'pi pi-list-check', 6, TRUE, 4),
(27, 'Teacher Allocation', 'ACAD_TEACHER_ALLOCATION', 'Subject and workload assignment', '/app/academics/teacher-allocation', 'pi pi-user-plus', 7, TRUE, 4),
(28, 'Class Teacher Allocation', 'ACAD_CLASS_TEACHER', 'Class ownership assignment', '/app/academics/class-teacher-allocation', 'pi pi-id-card', 8, TRUE, 4),
(29, 'Timetable', 'ACAD_TIMETABLE', 'Academic timetable scheduler', '/app/academics/timetable', 'pi pi-table', 9, TRUE, 4),
(30, 'Academic Calendar', 'ACAD_CALENDAR', 'Academic calendar events and milestones', '/app/academics/calendar', 'pi pi-calendar', 10, TRUE, 4),
(31, 'Academic Hierarchy', 'ACAD_HIERARCHY', 'Academic hierarchy and capacity view', '/app/academics/hierarchy', 'pi pi-sitemap', 11, TRUE, 4),
(32, 'Academic Settings', 'ACAD_SETTINGS', 'Academic operating rules and preferences', '/app/academics/settings', 'pi pi-cog', 12, TRUE, 4);

-- ============================================
-- 11. SUBMENU-PRIVILEGE MAPPING
-- ============================================
INSERT INTO submenu_privilege_mapping (mapping_id, sub_menu_id, privilege_id) VALUES
(1,1,1),(2,2,1),(3,2,2),(4,2,3),(5,2,4),(6,3,1),(7,3,2),(8,3,3),(9,3,4),
(10,4,1),(11,4,2),(12,4,3),(13,4,4),(14,5,1),(15,5,2),(16,5,3),(17,5,4),
(18,6,1),(19,6,2),(20,6,3),(21,6,4),(22,7,1),(23,7,2),(24,7,3),(25,7,4),
(26,8,1),(27,8,2),(28,8,3),(29,9,1),(30,9,2),(31,9,3),(32,9,5),
(33,10,1),(34,10,2),(35,10,3),(36,10,4),(37,11,1),(38,11,2),(39,11,3),(40,11,4),
(41,12,1),(42,12,2),(43,12,3),(44,12,4),(45,12,5),(46,13,1),(47,13,2),(48,13,3),
(49,14,1),(50,14,2),(51,14,3),(52,15,1),(53,15,2),(54,15,3),
(55,16,1),(56,16,2),(57,16,3),(58,17,1),(59,17,2),(60,17,3),
(61,18,1),(62,18,2),(63,18,3),(64,18,4),(65,19,1),(66,19,2),(67,19,3),
(68,20,1),(69,20,2),(70,20,3),(71,20,4),(72,21,1),(73,21,2),(74,21,3),(75,21,4),
(76,22,1),(77,22,2),(78,22,3),
(79,23,1),(80,23,2),(81,23,3),(82,23,4),
(83,24,1),(84,24,2),(85,24,3),(86,24,4),
(87,25,1),(88,25,2),(89,25,3),(90,25,4);

INSERT INTO submenu_privilege_mapping (mapping_id, sub_menu_id, privilege_id) VALUES
(91,26,1),(92,26,2),(93,26,3),(94,26,4),
(95,27,1),(96,27,2),(97,27,3),(98,27,4),
(99,28,1),(100,28,2),(101,28,3),(102,28,4),
(103,29,1),(104,29,2),(105,29,3),(106,29,4),
(107,30,1),(108,30,2),(109,30,3),(110,30,4),
(111,31,1),(112,31,2),(113,31,3),(114,31,4),
(115,32,1),(116,32,2),(117,32,3),(118,32,4);

-- ============================================
-- 12. ROLE-SUBMENU-PRIVILEGE MAPPING
-- ============================================
INSERT INTO role_submenu_privilege_mapping (mapping_id, role_id, sub_menu_id, privilege_id) VALUES
-- SUPER_ADMIN: all
(1,1,1,1),(2,1,2,1),(3,1,2,2),(4,1,2,3),(5,1,2,4),
(6,1,3,1),(7,1,3,2),(8,1,3,3),(9,1,3,4),(10,1,4,1),(11,1,4,2),(12,1,4,3),(13,1,4,4),
(14,1,5,1),(15,1,5,2),(16,1,5,3),(17,1,5,4),(18,1,6,1),(19,1,6,2),(20,1,6,3),(21,1,6,4),
(22,1,7,1),(23,1,7,2),(24,1,7,3),(25,1,7,4),(26,1,8,1),(27,1,8,2),(28,1,8,3),
(29,1,9,1),(30,1,9,2),(31,1,9,3),(32,1,9,5),
(33,1,10,1),(34,1,10,2),(35,1,10,3),(36,1,10,4),(37,1,11,1),(38,1,11,2),(39,1,11,3),(40,1,11,4),
(41,1,12,1),(42,1,12,2),(43,1,12,3),(44,1,12,4),(45,1,12,5),
(46,1,13,1),(47,1,13,2),(48,1,13,3),(49,1,14,1),(50,1,14,2),(51,1,14,3),
(52,1,15,1),(53,1,15,2),(54,1,15,3),(55,1,16,1),(56,1,16,2),(57,1,16,3),
(58,1,17,1),(59,1,17,2),(60,1,17,3),(61,1,18,1),(62,1,18,2),(63,1,18,3),(64,1,18,4),
(65,1,19,1),(66,1,19,2),(67,1,19,3),(68,1,20,1),(69,1,20,2),(70,1,20,3),(71,1,20,4),
(72,1,21,1),(73,1,21,2),(74,1,21,3),(75,1,21,4),(76,1,22,1),(77,1,22,2),(78,1,22,3),
-- ADMIN
(79,2,1,1),(80,2,2,1),(81,2,2,2),(82,2,2,3),(83,2,2,4),
(84,2,3,1),(85,2,3,2),(86,2,3,3),(87,2,5,1),(88,2,5,2),(89,2,5,3),(90,2,5,4),
(91,2,10,1),(92,2,10,2),(93,2,11,1),(94,2,11,2),(95,2,12,1),(96,2,12,2),(97,2,12,5),
(98,2,15,1),(99,2,15,2),(100,2,18,1),(101,2,18,2),(102,2,18,3),
-- TEACHER
(103,3,1,1),(104,3,10,1),(105,3,11,1),(106,3,12,1),(107,3,15,1),(108,3,15,2),(109,3,2,1),
-- SUPER_ADMIN: menu administration pages
(110,1,23,1),(111,1,23,2),(112,1,23,3),(113,1,23,4),
(114,1,24,1),(115,1,24,2),(116,1,24,3),(117,1,24,4),
(118,1,25,1),(119,1,25,2),(120,1,25,3),(121,1,25,4),
-- ADMIN: simplified administration pages
(122,2,20,1),(123,2,20,3),(124,2,22,1),(125,2,22,3),(126,2,23,1),(127,2,23,3);

INSERT INTO role_submenu_privilege_mapping (mapping_id, role_id, sub_menu_id, privilege_id) VALUES
-- SUPER_ADMIN: complete academic workspace
(128,1,26,1),(129,1,26,2),(130,1,26,3),(131,1,26,4),
(132,1,27,1),(133,1,27,2),(134,1,27,3),(135,1,27,4),
(136,1,28,1),(137,1,28,2),(138,1,28,3),(139,1,28,4),
(140,1,29,1),(141,1,29,2),(142,1,29,3),(143,1,29,4),
(144,1,30,1),(145,1,30,2),(146,1,30,3),(147,1,30,4),
(148,1,31,1),(149,1,31,2),(150,1,31,3),(151,1,31,4),
(152,1,32,1),(153,1,32,2),(154,1,32,3),(155,1,32,4),
-- ADMIN: operate academic workspace
(156,2,26,1),(157,2,26,2),(158,2,26,3),
(159,2,27,1),(160,2,27,2),(161,2,27,3),
(162,2,28,1),(163,2,28,2),(164,2,28,3),
(165,2,29,1),(166,2,29,2),(167,2,29,3),
(168,2,30,1),(169,2,30,2),(170,2,30,3),
(171,2,31,1),(172,2,31,2),(173,2,31,3),
(174,2,32,1),(175,2,32,2),(176,2,32,3),
-- TEACHER: academic workspace visibility
(177,3,26,1),(178,3,27,1),(179,3,28,1),(180,3,29,1),(181,3,30,1),(182,3,31,1);

-- ============================================
-- 13. DEPARTMENTS
-- ============================================
INSERT INTO department (department_id, department_name, description, department_code, is_active, organization_id) VALUES
(1, 'Mathematics', 'Mathematics Department', 'DEPT-MATH', TRUE, 1),
(2, 'Science', 'Science and Laboratory Department', 'DEPT-SCI', TRUE, 1),
(3, 'English', 'English Language and Literature', 'DEPT-ENG', TRUE, 1),
(4, 'Computer Science', 'Computer Science and IT', 'DEPT-CS', TRUE, 1),
(5, 'Administration', 'Administrative Department', 'DEPT-ADMIN', TRUE, 1);

-- ============================================
-- 14. BRANCHES
-- ============================================
INSERT INTO branch (branch_id, branch_name, location, branch_code, is_active, organization_id) VALUES
(1, 'Main Campus', 'Bangalore, MG Road', 'BR-MAIN', TRUE, 1),
(2, 'Whitefield Campus', 'Bangalore, Whitefield', 'BR-WF', TRUE, 1);

-- ============================================
-- 14A. ADDITIONAL ACADEMIC STAFF USERS
-- ============================================
INSERT INTO users (id, user_code, first_name, middle_name, last_name, email, mobile_number, user_name, password, address, city, state, country, zip_code, gender, is_blocked, is_2fa_enabled, attempts, is_first_time_login, is_email_verified, is_mobile_verified, date_of_birth, last_login_date) VALUES
(11, 'USR011', 'Nisha', NULL, 'Iyer', 'nisha.iyer@thinkerscave.com', 9876543222, 'teacher3', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '18 Basavanagudi', 'Bangalore', 'Karnataka', 'India', '560004', 'Female', FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1993-02-14', '2026-05-20'),
(12, 'USR012', 'Farhan', NULL, 'Khan', 'farhan.khan@thinkerscave.com', 9876543223, 'teacher4', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '91 Richmond Town', 'Bangalore', 'Karnataka', 'India', '560025', 'Male', FALSE, FALSE, 0, FALSE, TRUE, TRUE, '1987-09-21', '2026-05-20');

INSERT INTO user_roles (user_id, role_id) VALUES
(11, 3), (12, 3);

INSERT INTO organization_users (id, organization_id, user_id, role_name, is_active, joined_at, updated_at) VALUES
(11, 1, 11, 'TEACHER', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 1, 12, 'TEACHER', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_tenant_mapping (email, username, tenant_id, is_active) VALUES
('nisha.iyer@thinkerscave.com', 'teacher3', 'public', TRUE),
('farhan.khan@thinkerscave.com', 'teacher4', 'public', TRUE);

-- ============================================
-- 15. STAFF
-- ============================================
INSERT INTO staff (staff_id, staff_code, first_name, middle_name, last_name, email, mobile_number, gender, date_of_birth, hire_date, address, city, state, remarks, is_active, organization_id, user_id, branch_id, department_id) VALUES
(1, 'STF001', 'Amit', 'K', 'Verma', 'amit.verma@thinkerscave.com', 9876543212, 'Male', '1990-11-10', '2021-06-01', '78 Residency Road', 'Bangalore', 'Karnataka', 'Senior Math Teacher', TRUE, 1, 3, 1, 1),
(2, 'STF002', 'Sunita', NULL, 'Patel', 'sunita.patel@thinkerscave.com', 9876543213, 'Female', '1992-04-05', '2022-01-15', '22 Brigade Road', 'Bangalore', 'Karnataka', 'Science Teacher', TRUE, 1, 4, 1, 2);

INSERT INTO staff (staff_id, staff_code, first_name, middle_name, last_name, email, mobile_number, gender, date_of_birth, hire_date, address, city, state, remarks, is_active, organization_id, user_id, branch_id, department_id) VALUES
(3, 'STF003', 'Nisha', NULL, 'Iyer', 'nisha.iyer@thinkerscave.com', 9876543222, 'Female', '1993-02-14', '2023-04-10', '18 Basavanagudi', 'Bangalore', 'Karnataka', 'English and Humanities Faculty', TRUE, 1, 11, 1, 3),
(4, 'STF004', 'Farhan', NULL, 'Khan', 'farhan.khan@thinkerscave.com', 9876543223, 'Male', '1987-09-21', '2020-07-12', '91 Richmond Town', 'Bangalore', 'Karnataka', 'Computer Science and STEM Faculty', TRUE, 1, 12, 1, 4);

-- ============================================
-- 16. CLASSES
-- ============================================
INSERT INTO "CLASS" (class_id, class_name, organization_id) VALUES
(1, 'Class 8', 1), (2, 'Class 9', 1), (3, 'Class 10', 1),
(4, 'Class 11 - Science', 1), (5, 'Class 11 - Commerce', 1),
(6, 'Class 12 - Science', 1), (7, 'Class 12 - Commerce', 1);

-- ============================================
-- 17. SECTIONS
-- ============================================
INSERT INTO section (section_id, section_name, class_entity_class_id) VALUES
(1, 'Section A', 1), (2, 'Section B', 1),
(3, 'Section A', 2), (4, 'Section B', 2),
(5, 'Section A', 3), (6, 'Section B', 3),
(7, 'Section A', 4), (8, 'Section A', 5),
(9, 'Section A', 6), (10, 'Section A', 7);

-- ============================================
-- 18. GUARDIANS (has own created_at/updated_at, NOT Auditable)
-- ============================================
INSERT INTO guardian (guardian_id, first_name, middle_name, last_name, relation, email, mobile_number, address, created_at, updated_at) VALUES
(1, 'Meera', NULL, 'Nair', 'Mother', 'meera.nair@thinkerscave.com', 9876543217, '56 Koramangala, Bangalore', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Suresh', NULL, 'Reddy', 'Father', 'suresh.reddy@gmail.com', 9876543220, '34 Whitefield, Bangalore', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Arun', NULL, 'Malhotra', 'Father', 'arun.malhotra@gmail.com', 9876543221, '89 Indiranagar, Bangalore', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================
-- 19. ADDRESSES (for students)
-- ============================================
INSERT INTO address (id, country, state, city, zip_code, address_line) VALUES
(1, 'India', 'Karnataka', 'Bangalore', '560034', '56 Koramangala, 1st Block'),
(2, 'India', 'Karnataka', 'Bangalore', '560034', '56 Koramangala, 1st Block'),
(3, 'India', 'Karnataka', 'Bangalore', '560066', '34 Whitefield Main Road'),
(4, 'India', 'Karnataka', 'Bangalore', '560066', '34 Whitefield Main Road'),
(5, 'India', 'Karnataka', 'Bangalore', '560038', '89 Indiranagar, 3rd Stage'),
(6, 'India', 'Karnataka', 'Bangalore', '560038', '89 Indiranagar, 3rd Stage');

-- ============================================
-- 20. STUDENTS
-- ============================================
INSERT INTO student (student_id, first_name, last_name, email, mobile_number, gender, age, is_same_address, date_of_birth, enrollment_date, roll_number, remarks, is_active, organization_id, current_address_id, permanent_address_id, class_id, section_id, user_id, guardian_id) VALUES
(1, 'Rahul', 'Singh', 'rahul.singh@thinkerscave.com', 9876543214, 'Male', 17, TRUE, '2008-09-12', '2024-06-15', 'TC-2024-001', 'Good at math', TRUE, 1, 1, 2, 3, 5, 5, 1),
(2, 'Ananya', 'Reddy', 'ananya.reddy@thinkerscave.com', 9876543215, 'Female', 16, FALSE, '2009-01-25', '2024-06-16', 'TC-2024-002', 'Science enthusiast', TRUE, 1, 3, 4, 2, 3, 6, 2),
(3, 'Vikram', 'Malhotra', 'vikram.malhotra@thinkerscave.com', 9876543216, 'Male', 17, NULL, '2008-06-18', '2024-06-17', 'TC-2024-003', 'Sports captain', TRUE, 1, 5, 6, 3, 5, 7, 3);

-- ============================================
-- 21. COURSES
-- ============================================
INSERT INTO courses (course_id, course_code, course_name, description, duration_months, duration_years, level, degree_type, total_credits, min_credits_required, category, total_semesters, is_active, organization_id) VALUES
(1, 'CBSE-10', 'CBSE Class 10 Program', 'Central Board secondary education', 12, 1, 'SECONDARY', 'CERTIFICATE', 40, 36, 'ACADEMIC', 2, TRUE, 1),
(2, 'CBSE-12-SCI', 'CBSE Class 12 Science', 'Higher secondary science stream', 24, 2, 'HIGHER_SECONDARY', 'CERTIFICATE', 50, 45, 'ACADEMIC', 4, TRUE, 1),
(3, 'CBSE-12-COM', 'CBSE Class 12 Commerce', 'Higher secondary commerce stream', 24, 2, 'HIGHER_SECONDARY', 'CERTIFICATE', 48, 42, 'ACADEMIC', 4, TRUE, 1);

-- ============================================
-- 22. SUBJECTS
-- ============================================
INSERT INTO subjects (subject_id, subject_code, subject_name, description, credits, category, theory_hours, practical_hours, lab_hours, is_active, max_marks, passing_marks, organization_id) VALUES
(1, 'MATH-10', 'Mathematics', 'CBSE Class 10 Mathematics', 5, 'CORE', 4, 0, 0, TRUE, 100, 33, 1),
(2, 'SCI-10', 'Science', 'CBSE Class 10 Science', 5, 'CORE', 3, 1, 1, TRUE, 100, 33, 1),
(3, 'ENG-10', 'English', 'CBSE English Language and Literature', 5, 'CORE', 4, 0, 0, TRUE, 100, 33, 1),
(4, 'SST-10', 'Social Science', 'History, Geography, Political Science', 4, 'CORE', 4, 0, 0, TRUE, 100, 33, 1),
(5, 'HIN-10', 'Hindi', 'Hindi Language and Literature', 4, 'CORE', 3, 0, 0, TRUE, 100, 33, 1),
(6, 'CS-10', 'Computer Science', 'Introduction to Programming', 3, 'ELECTIVE', 2, 0, 2, TRUE, 100, 33, 1),
(7, 'PHY-12', 'Physics', 'CBSE Class 12 Physics', 5, 'CORE', 3, 0, 2, TRUE, 100, 33, 1),
(8, 'CHEM-12', 'Chemistry', 'CBSE Class 12 Chemistry', 5, 'CORE', 3, 0, 2, TRUE, 100, 33, 1);

-- ============================================
-- 23. ACADEMIC YEARS
-- ============================================
INSERT INTO academic_years (academic_year_id, year_code, year_name, start_date, end_date, is_current, is_active, description, organization_id) VALUES
(1, 'AY-2025-26', 'Academic Year 2025-26', '2025-04-01', '2026-03-31', TRUE, TRUE, 'Current academic year', 1),
(2, 'AY-2024-25', 'Academic Year 2024-25', '2024-04-01', '2025-03-31', FALSE, TRUE, 'Previous academic year', 1);

-- ============================================
-- 23A. ACADEMIC CONTAINERS
-- ============================================
INSERT INTO academic_containers (container_id, container_type, container_code, container_name, description, organization_id, academic_year_id, course_id, parent_container_id, level, capacity, current_strength, display_order, is_active, metadata) VALUES
(1, 'CLASS', 'AY25-C08', 'Class 8', 'Middle school learning cohort for the current academic year', 1, 1, 1, NULL, 1, 80, 42, 1, TRUE, '{"wing":"North","shift":"Morning"}'),
(2, 'CLASS', 'AY25-C09', 'Class 9', 'Foundation cohort for secondary readiness', 1, 1, 1, NULL, 1, 80, 47, 2, TRUE, '{"wing":"North","shift":"Morning"}'),
(3, 'CLASS', 'AY25-C10', 'Class 10', 'Board examination cohort with focused delivery governance', 1, 1, 1, NULL, 1, 90, 58, 3, TRUE, '{"wing":"East","shift":"Morning","board":"CBSE"}'),
(4, 'CLASS', 'AY25-C11-SCI', 'Class 11 - Science', 'Higher secondary science stream cohort', 1, 1, 2, NULL, 1, 60, 34, 4, TRUE, '{"wing":"Science","labAccess":true}'),
(5, 'CLASS', 'AY25-C11-COM', 'Class 11 - Commerce', 'Higher secondary commerce stream cohort', 1, 1, 3, NULL, 1, 60, 29, 5, TRUE, '{"wing":"Commerce","labAccess":false}'),
(6, 'CLASS', 'AY25-C12-SCI', 'Class 12 - Science', 'Final-year science stream cohort', 1, 1, 2, NULL, 1, 60, 38, 6, TRUE, '{"wing":"Science","labAccess":true}'),
(7, 'CLASS', 'AY25-C12-COM', 'Class 12 - Commerce', 'Final-year commerce stream cohort', 1, 1, 3, NULL, 1, 60, 31, 7, TRUE, '{"wing":"Commerce","labAccess":false}');

INSERT INTO academic_containers (container_id, container_type, container_code, container_name, description, organization_id, academic_year_id, course_id, parent_container_id, level, capacity, current_strength, display_order, is_active, metadata) VALUES
(8, 'SECTION', 'AY25-C08-A', 'Class 8 - Section A', 'Primary section for Class 8 morning batch', 1, 1, 1, 1, 2, 40, 22, 1, TRUE, '{"room":"A-201","mentor":"Nisha Iyer"}'),
(9, 'SECTION', 'AY25-C08-B', 'Class 8 - Section B', 'Second section for Class 8 morning batch', 1, 1, 1, 1, 2, 40, 20, 2, TRUE, '{"room":"A-202"}'),
(10, 'SECTION', 'AY25-C09-A', 'Class 9 - Section A', 'Primary section for Class 9', 1, 1, 1, 2, 2, 40, 24, 1, TRUE, '{"room":"A-301"}'),
(11, 'SECTION', 'AY25-C09-B', 'Class 9 - Section B', 'Second section for Class 9', 1, 1, 1, 2, 2, 40, 23, 2, TRUE, '{"room":"A-302"}'),
(12, 'SECTION', 'AY25-C10-A', 'Class 10 - Section A', 'Board cohort section A', 1, 1, 1, 3, 2, 45, 30, 1, TRUE, '{"room":"B-101","boardFocus":true}'),
(13, 'SECTION', 'AY25-C10-B', 'Class 10 - Section B', 'Board cohort section B', 1, 1, 1, 3, 2, 45, 28, 2, TRUE, '{"room":"B-102","boardFocus":true}'),
(14, 'SECTION', 'AY25-C11-SCI-A', 'Class 11 Science - Section A', 'Science stream section with lab linkage', 1, 1, 2, 4, 2, 60, 34, 1, TRUE, '{"room":"S-101","lab":"Physics Lab"}'),
(15, 'SECTION', 'AY25-C11-COM-A', 'Class 11 Commerce - Section A', 'Commerce stream section', 1, 1, 3, 5, 2, 60, 29, 1, TRUE, '{"room":"C-101"}'),
(16, 'SECTION', 'AY25-C12-SCI-A', 'Class 12 Science - Section A', 'Final-year science stream section', 1, 1, 2, 6, 2, 60, 38, 1, TRUE, '{"room":"S-201","lab":"Chemistry Lab"}'),
(17, 'SECTION', 'AY25-C12-COM-A', 'Class 12 Commerce - Section A', 'Final-year commerce stream section', 1, 1, 3, 7, 2, 60, 31, 1, TRUE, '{"room":"C-201"}');

-- ============================================
-- 24. SEMESTERS
-- ============================================
INSERT INTO semesters (semester_id, semester_name, semester_number, start_date, end_date, is_current, is_active, description, academic_year_id, organization_id) VALUES
(1, 'Term 1', 1, '2025-04-01', '2025-09-30', FALSE, TRUE, 'First term', 1, 1),
(2, 'Term 2', 2, '2025-10-01', '2026-03-31', TRUE, TRUE, 'Second term', 1, 1);

-- ============================================
-- 25. COURSE-SUBJECT MAPPING
-- ============================================
INSERT INTO course_subject_mapping (mapping_id, course_id, subject_id, semester, is_mandatory, is_active, display_order, organization_id) VALUES
(1, 1, 1, 1, TRUE, TRUE, 1, 1), (2, 1, 2, 1, TRUE, TRUE, 2, 1),
(3, 1, 3, 1, TRUE, TRUE, 3, 1), (4, 1, 4, 1, TRUE, TRUE, 4, 1),
(5, 1, 5, 1, TRUE, TRUE, 5, 1), (6, 1, 6, 1, FALSE, TRUE, 6, 1),
(7, 2, 7, 1, TRUE, TRUE, 1, 1), (8, 2, 8, 1, TRUE, TRUE, 2, 1);

-- ============================================
-- 25A. TEACHER ALLOCATIONS
-- ============================================
INSERT INTO class_subject_teacher (mapping_id, class_id, organization_id, section_id, subject_id, teacher_id, academic_year_id, semester_id, periods_per_week, is_active) VALUES
(1, 3, 1, 5, 1, 1, 1, 2, 5, TRUE),
(2, 3, 1, 5, 2, 2, 1, 2, 5, TRUE),
(3, 2, 1, 3, 3, 3, 1, 2, 4, TRUE),
(4, 1, 1, 1, 6, 4, 1, 2, 3, TRUE),
(5, 4, 1, 7, 7, 2, 1, 2, 5, TRUE),
(6, 4, 1, 7, 8, 4, 1, 2, 5, TRUE),
(7, 6, 1, 9, 7, 2, 1, 2, 5, TRUE),
(8, 5, 1, 8, 3, 3, 1, 2, 4, TRUE),
(9, 2, 1, 4, 1, 1, 1, 2, 5, TRUE),
(10, 3, 1, 6, 4, 3, 1, 2, 4, TRUE);

-- ============================================
-- 25B. CLASS TEACHER OWNERSHIP
-- ============================================
INSERT INTO class_teacher_assignment (assignment_id, organization_id, academic_year_id, class_id, section_id, teacher_id, effective_from, effective_to, is_active, notes) VALUES
(1, 1, 1, 3, 5, 1, '2025-04-01', NULL, TRUE, 'Board readiness mentor for Class 10 Section A.'),
(2, 1, 1, 4, 7, 2, '2025-04-01', NULL, TRUE, 'Science stream academic owner and parent liaison.');

-- ============================================
-- 25C. TIMETABLE SLOTS
-- ============================================
INSERT INTO timetable_slot (slot_id, organization_id, academic_year_id, class_id, section_id, subject_id, teacher_id, day_of_week, period_number, start_time, end_time, room_name, is_active) VALUES
(1, 1, 1, 3, 5, 1, 1, 'MONDAY', 1, '08:30:00', '09:15:00', 'B-101', TRUE),
(2, 1, 1, 3, 5, 2, 2, 'MONDAY', 2, '09:20:00', '10:05:00', 'Science Lab 1', TRUE),
(3, 1, 1, 2, 3, 3, 3, 'TUESDAY', 1, '08:30:00', '09:15:00', 'A-301', TRUE),
(4, 1, 1, 1, 1, 6, 4, 'TUESDAY', 2, '09:20:00', '10:05:00', 'Computer Lab', TRUE),
(5, 1, 1, 4, 7, 7, 2, 'WEDNESDAY', 1, '08:30:00', '09:15:00', 'Physics Lab', TRUE),
(6, 1, 1, 4, 7, 8, 4, 'WEDNESDAY', 2, '09:20:00', '10:05:00', 'Chemistry Lab', TRUE),
(7, 1, 1, 5, 8, 3, 3, 'THURSDAY', 3, '10:20:00', '11:05:00', 'C-101', TRUE),
(8, 1, 1, 3, 6, 4, 3, 'FRIDAY', 4, '11:10:00', '11:55:00', 'B-102', TRUE);

-- ============================================
-- 25D. ACADEMIC CALENDAR EVENTS
-- ============================================
INSERT INTO academic_calendar_event (event_id, organization_id, academic_year_id, title, event_type, start_date, end_date, all_day, is_active, description) VALUES
(1, 1, 1, 'Term 2 Curriculum Freeze', 'DEADLINE', '2026-01-10', '2026-01-10', TRUE, TRUE, 'Final date for departments to lock Term 2 syllabus pacing.'),
(2, 1, 1, 'Class 10 Board Mock Assessment', 'EXAM', '2026-01-20', '2026-01-24', TRUE, TRUE, 'Full mock assessment cycle for Class 10 board cohort.'),
(3, 1, 1, 'Republic Day Holiday', 'HOLIDAY', '2026-01-26', '2026-01-26', TRUE, TRUE, 'Campus closed for Republic Day.'),
(4, 1, 1, 'Parent Academic Review', 'MEETING', '2026-02-07', '2026-02-07', TRUE, TRUE, 'Section-wise academic review meeting with parents.'),
(5, 1, 1, 'Annual Exhibition Week', 'EVENT', '2026-02-16', '2026-02-20', TRUE, TRUE, 'Integrated academic showcase across science, commerce and humanities.');

-- ============================================
-- 25E. ACADEMIC SETTINGS
-- ============================================
INSERT INTO academic_setting (setting_id, organization_id, setting_key, setting_value, value_type, category, is_active, description) VALUES
(1, 1, 'GRADING_SCALE', 'LETTER', 'TEXT', 'ASSESSMENT', TRUE, 'Default grading scale used across academic evaluations.'),
(2, 1, 'PERIODS_PER_DAY', '8', 'NUMBER', 'TIMETABLE', TRUE, 'Default number of instructional periods per day.'),
(3, 1, 'ATTENDANCE_LINKAGE', 'true', 'BOOLEAN', 'ATTENDANCE', TRUE, 'Controls whether timetable periods feed attendance workflows.'),
(4, 1, 'PROMOTION_RULE', 'ANNUAL_REVIEW', 'TEXT', 'PROMOTION', TRUE, 'Default promotion evaluation strategy.'),
(5, 1, 'SECTION_CAPACITY', '40', 'NUMBER', 'STRUCTURE', TRUE, 'Default capacity used when creating new sections.');

-- ============================================
-- 26. SYLLABUS
-- ============================================
INSERT INTO syllabus (syllabus_id, syllabus_code, title, description, total_hours, version, status, is_active, subject_id, academic_year_id, organization_id) VALUES
(1, 'SYL-MATH-10-2025', 'Mathematics Class 10', 'Complete CBSE Math syllabus', 180, '1.0', 'PUBLISHED', TRUE, 1, 1, 1),
(2, 'SYL-SCI-10-2025', 'Science Class 10', 'Complete CBSE Science syllabus', 200, '1.0', 'PUBLISHED', TRUE, 2, 1, 1),
(3, 'SYL-ENG-10-2025', 'English Class 10', 'CBSE English syllabus', 160, '1.0', 'APPROVED', TRUE, 3, 1, 1);

INSERT INTO syllabus (syllabus_id, syllabus_code, title, description, total_hours, version, status, is_active, subject_id, academic_year_id, organization_id) VALUES
(4, 'SYL-SST-10-2025', 'Social Science Class 10', 'Integrated history, civics, geography and economics plan', 150, '1.0', 'PUBLISHED', TRUE, 4, 1, 1),
(5, 'SYL-HIN-10-2025', 'Hindi Class 10', 'Hindi language and literature delivery plan', 140, '1.0', 'APPROVED', TRUE, 5, 1, 1),
(6, 'SYL-CS-10-2025', 'Computer Science Class 10', 'Programming fundamentals and digital literacy plan', 120, '1.0', 'PUBLISHED', TRUE, 6, 1, 1),
(7, 'SYL-PHY-12-2025', 'Physics Class 12', 'Senior secondary physics theory and lab curriculum', 190, '1.0', 'PUBLISHED', TRUE, 7, 1, 1),
(8, 'SYL-CHEM-12-2025', 'Chemistry Class 12', 'Senior secondary chemistry theory and lab curriculum', 190, '1.0', 'PUBLISHED', TRUE, 8, 1, 1);

-- ============================================
-- 27. CHAPTERS
-- ============================================
INSERT INTO chapters (chapter_id, chapter_name, chapter_number, description, estimated_hours, learning_objectives, is_active, syllabus_id) VALUES
(1, 'Real Numbers', 1, 'Properties of real numbers', 15, 'Understand real number properties', TRUE, 1),
(2, 'Polynomials', 2, 'Zeros of polynomials', 20, 'Find zeros and verify relationships', TRUE, 1),
(3, 'Pair of Linear Equations', 3, 'Solving linear equations', 25, 'Solve using multiple methods', TRUE, 1),
(4, 'Quadratic Equations', 4, 'Standard form, factorization', 25, 'Solve quadratic equations', TRUE, 1),
(5, 'Trigonometry', 5, 'Ratios, identities, heights', 30, 'Apply trigonometric concepts', TRUE, 1),
(6, 'Chemical Reactions', 1, 'Types of chemical reactions', 20, 'Identify and balance reactions', TRUE, 2),
(7, 'Acids, Bases and Salts', 2, 'Properties, pH scale', 18, 'Understand pH concept', TRUE, 2),
(8, 'Light', 3, 'Reflection and Refraction', 25, 'Apply laws of optics', TRUE, 2);

INSERT INTO chapters (chapter_id, chapter_name, chapter_number, description, estimated_hours, learning_objectives, is_active, syllabus_id) VALUES
(9, 'Democratic Politics', 1, 'Institutions, participation and constitutional values', 24, 'Interpret political systems and civic responsibilities', TRUE, 4),
(10, 'Hindi Kavy Khand', 1, 'Poetry appreciation and literary analysis', 22, 'Analyze themes, style and expression in prescribed poems', TRUE, 5),
(11, 'Programming Basics', 1, 'Algorithms, variables and control flow', 28, 'Write simple programs using structured logic', TRUE, 6),
(12, 'Electrostatics', 1, 'Charges, fields and potential', 30, 'Apply electrostatic principles to numerical and lab problems', TRUE, 7),
(13, 'Solutions and Electrochemistry', 1, 'Concentration, cells and reactions', 32, 'Connect chemical theory with practical observations', TRUE, 8);

-- ============================================
-- 28. TOPICS
-- ============================================
INSERT INTO topics (topic_id, topic_name, topic_number, description, estimated_hours, is_active, chapter_id) VALUES
(1, 'Euclids Division Lemma', 1, 'Statement and proof', 3, TRUE, 1),
(2, 'Fundamental Theorem of Arithmetic', 2, 'Prime factorization', 4, TRUE, 1),
(3, 'Irrational Numbers', 3, 'Proving irrationality', 4, TRUE, 1),
(4, 'Decimal Expansions', 4, 'Rational number decimals', 4, TRUE, 1),
(5, 'Geometrical Meaning of Zeros', 1, 'Graphs and zeros', 5, TRUE, 2),
(6, 'Zeros and Coefficients', 2, 'Sum and product of zeros', 7, TRUE, 2),
(7, 'Division Algorithm', 3, 'Polynomial division', 8, TRUE, 2),
(8, 'Chemical Equations', 1, 'Writing and balancing', 5, TRUE, 6),
(9, 'Types of Reactions', 2, 'Combination, decomposition', 8, TRUE, 6),
(10, 'Oxidation in Daily Life', 3, 'Corrosion and rancidity', 7, TRUE, 6);

INSERT INTO topics (topic_id, topic_name, topic_number, description, estimated_hours, is_active, chapter_id) VALUES
(11, 'Federalism', 1, 'Division of powers and democratic participation', 8, TRUE, 9),
(12, 'Political Parties', 2, 'Party systems, challenges and reforms', 8, TRUE, 9),
(13, 'Kavita Pathan', 1, 'Guided poetry reading and recitation', 8, TRUE, 10),
(14, 'Sahityik Vishleshan', 2, 'Theme, imagery and language analysis', 8, TRUE, 10),
(15, 'Variables and Data Types', 1, 'Core programming constructs', 8, TRUE, 11),
(16, 'Conditionals and Loops', 2, 'Decision making and repetition', 10, TRUE, 11),
(17, 'Electric Field', 1, 'Field intensity and field lines', 10, TRUE, 12),
(18, 'Electric Potential', 2, 'Potential, energy and equipotential surfaces', 10, TRUE, 12),
(19, 'Concentration Terms', 1, 'Molarity, molality and solution strength', 10, TRUE, 13),
(20, 'Electrochemical Cells', 2, 'Cell potential and applications', 10, TRUE, 13);

-- ============================================
-- 29. ATTENDANCE
-- ============================================
INSERT INTO attendance (id, organization_id, attendance_type, reference_id, reference_name, attendance_date, status, class_id, class_name, section_name, shift, department, room_number, remarks, marked_by) VALUES
(1, 1, 'CLASS', 1, 'Rahul Singh', '2026-05-20', 'PRESENT', 3, 'Class 10', 'Section A', 'Morning', NULL, 'A-101', NULL, 'teacher1'),
(2, 1, 'CLASS', 2, 'Ananya Reddy', '2026-05-20', 'PRESENT', 2, 'Class 9', 'Section A', 'Morning', NULL, 'A-102', NULL, 'teacher1'),
(3, 1, 'CLASS', 3, 'Vikram Malhotra', '2026-05-20', 'ABSENT', 3, 'Class 10', 'Section A', 'Morning', NULL, 'A-101', 'Medical leave', 'teacher1'),
(4, 1, 'CLASS', 1, 'Rahul Singh', '2026-05-19', 'PRESENT', 3, 'Class 10', 'Section A', 'Morning', NULL, 'A-101', NULL, 'teacher1'),
(5, 1, 'CLASS', 2, 'Ananya Reddy', '2026-05-19', 'LATE', 2, 'Class 9', 'Section A', 'Morning', NULL, 'A-102', 'Arrived 10 min late', 'teacher1'),
(6, 1, 'CLASS', 3, 'Vikram Malhotra', '2026-05-19', 'PRESENT', 3, 'Class 10', 'Section A', 'Morning', NULL, 'A-101', NULL, 'teacher1'),
(7, 1, 'STAFF', 1, 'Amit K Verma', '2026-05-20', 'PRESENT', NULL, NULL, NULL, 'Morning', 'Mathematics', NULL, NULL, 'admin'),
(8, 1, 'STAFF', 2, 'Sunita Patel', '2026-05-20', 'PRESENT', NULL, NULL, NULL, 'Morning', 'Science', NULL, NULL, 'admin'),
(9, 1, 'STAFF', 1, 'Amit K Verma', '2026-05-19', 'PRESENT', NULL, NULL, NULL, 'Morning', 'Mathematics', NULL, NULL, 'admin'),
(10, 1, 'STAFF', 2, 'Sunita Patel', '2026-05-19', 'WFH', NULL, NULL, NULL, 'Morning', 'Science', NULL, 'Working from home', 'admin');

-- ============================================
-- 30. INQUIRIES
-- ============================================
INSERT INTO inquiry (inquiry_id, name, mobile_number, email, class_interested_in, address, inquiry_source, referred_by, comments, assigned_counselor_id, status, is_deleted, last_follow_up_date) VALUES
(1, 'Arjun Kapoor', '9988776601', 'arjun.kapoor@gmail.com', 'Class 10', '23 MG Road, Bangalore', 'WEBSITE', NULL, 'Interested in CBSE curriculum', 9, 'NEW', FALSE, NULL),
(2, 'Sneha Gupta', '9988776602', 'sneha.gupta@gmail.com', 'Class 9', '45 HSR Layout', 'WALK_IN', 'Mr. Rajan', 'Visited campus', 9, 'CONTACTED', FALSE, '2026-05-18 10:30:00'),
(3, 'Karthik Iyer', '9988776603', 'karthik.i@gmail.com', 'Class 11 - Science', '67 Jayanagar', 'PHONE', NULL, 'Asking about science stream', 9, 'FOLLOW_UP_REQUIRED', FALSE, '2026-05-19 14:00:00'),
(4, 'Preethi Nair', '9988776604', 'preethi.nair@gmail.com', 'Class 8', '12 Indiranagar', 'SOCIAL_MEDIA', NULL, 'Wants brochure', 9, 'READY_FOR_ADMISSION', FALSE, '2026-05-20 11:00:00'),
(5, 'Rohan Mehta', '9988776605', 'rohan.mehta@gmail.com', 'Class 10', '88 Koramangala', 'WEBSITE', NULL, 'Online inquiry, wants callback', NULL, 'NEW', FALSE, NULL);

-- ============================================
-- 31. FOLLOW-UPS
-- ============================================
INSERT INTO follow_up (id, follow_up_type, remarks, status_after_follow_up, follow_up_date, next_follow_up_date, inquiry_id) VALUES
(1, 'CALL', 'Called parent, discussed admission process', 'CONTACTED', '2026-05-18 10:30:00', '2026-05-22', 2),
(2, 'CALL', 'Explained science stream prerequisites', 'FOLLOW_UP_REQUIRED', '2026-05-19 14:00:00', '2026-05-23', 3),
(3, 'WHATSAPP', 'Sent brochure and fee structure', 'FOLLOW_UP_REQUIRED', '2026-05-19 16:00:00', '2026-05-25', 3),
(4, 'WALK_IN', 'Parent visited, ready to submit application', 'READY_FOR_ADMISSION', '2026-05-20 11:00:00', NULL, 4);

-- ============================================
-- 32. LEAVE REQUESTS
-- ============================================
INSERT INTO leave_requests (id, organization_id, staff_id, staff_name, department, leave_type, start_date, end_date, days, reason, status, applied_by, approved_by) VALUES
(1, 1, 1, 'Amit K Verma', 'Mathematics', 'SICK', '2026-05-25', '2026-05-26', 2, 'Fever and cold', 'PENDING', 'teacher1', NULL),
(2, 1, 2, 'Sunita Patel', 'Science', 'VACATION', '2026-06-01', '2026-06-05', 5, 'Family vacation', 'APPROVED', 'teacher2', 'admin'),
(3, 1, 1, 'Amit K Verma', 'Mathematics', 'PERSONAL', '2026-04-15', '2026-04-15', 1, 'Personal work', 'APPROVED', 'teacher1', 'admin');

-- ============================================
-- 33. STAFF PAYROLL
-- ============================================
INSERT INTO staff_payroll (id, organization_id, staff_id, staff_name, department, designation, basic, hra, special_allowance, academic_allowance, medical_allowance, travel_allowance, dearness_allowance, other_allowance, professional_tax, income_tax, provident_fund, effective_from) VALUES
(1, 1, 1, 'Amit K Verma', 'Mathematics', 'Senior Teacher', 45000.00, 18000.00, 5000.00, 3000.00, 2000.00, 3000.00, 2000.00, 0.00, 200.00, 5000.00, 5400.00, '2025-04-01'),
(2, 1, 2, 'Sunita Patel', 'Science', 'Teacher', 38000.00, 15200.00, 4000.00, 2500.00, 2000.00, 2500.00, 1500.00, 0.00, 200.00, 3500.00, 4560.00, '2025-04-01');

-- ============================================
-- 34. ADMISSION FORM TEMPLATE
-- ============================================
INSERT INTO admission_form_template (id, tenant_id, title, description, guidelines, is_active) VALUES
(1, 'public', 'Standard Admission Form 2025-26', 'Application form for admissions', 'Fill all required fields. Upload docs in PDF/JPG.', TRUE);

-- ============================================
-- 35. OWNER DETAILS
-- ============================================
INSERT INTO owner_details (owner_id, owner_code, owner_name, gender, owner_email, owner_mobile, user_id, org_id) VALUES
(1, 'OWN001', 'Rajesh Kumar', 'Male', 'admin@thinkerscave.com', '9876543210', 1, 1);

-- ============================================
-- 36. H2 IDENTITY RESTARTS FOR SEEDED DEV DATA
-- ============================================
ALTER TABLE users ALTER COLUMN id RESTART WITH 100;
ALTER TABLE department ALTER COLUMN department_id RESTART WITH 100;
ALTER TABLE branch ALTER COLUMN branch_id RESTART WITH 100;
ALTER TABLE staff ALTER COLUMN staff_id RESTART WITH 100;
ALTER TABLE "CLASS" ALTER COLUMN class_id RESTART WITH 100;
ALTER TABLE section ALTER COLUMN section_id RESTART WITH 100;
ALTER TABLE courses ALTER COLUMN course_id RESTART WITH 100;
ALTER TABLE subjects ALTER COLUMN subject_id RESTART WITH 100;
ALTER TABLE academic_years ALTER COLUMN academic_year_id RESTART WITH 100;
ALTER TABLE syllabus ALTER COLUMN syllabus_id RESTART WITH 100;
ALTER TABLE chapters ALTER COLUMN chapter_id RESTART WITH 100;
ALTER TABLE topics ALTER COLUMN topic_id RESTART WITH 100;
ALTER TABLE academic_containers ALTER COLUMN container_id RESTART WITH 100;
ALTER TABLE class_subject_teacher ALTER COLUMN mapping_id RESTART WITH 100;
ALTER TABLE class_teacher_assignment ALTER COLUMN assignment_id RESTART WITH 100;
ALTER TABLE timetable_slot ALTER COLUMN slot_id RESTART WITH 100;
ALTER TABLE academic_calendar_event ALTER COLUMN event_id RESTART WITH 100;
ALTER TABLE academic_setting ALTER COLUMN setting_id RESTART WITH 100;