package com.thinkerscave.finance.entity;

import com.thinkerscave.shared.entity.Auditable;
import jakarta.persistence.*;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@EqualsAndHashCode(callSuper = false, onlyExplicitlyIncluded = true)
@Table(name = "finance_configuration")
public class FinanceConfiguration extends Auditable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "finance_configuration_id")
    @EqualsAndHashCode.Include
    private Long financeConfigurationId;

    @Column(name = "auto_generate_dues", nullable = false)
    private Boolean autoGenerateDues = true;

    @Column(name = "generation_lead_days", nullable = false)
    private Integer generationLeadDays = 5;

    @Column(name = "default_due_day_for_new_structures", nullable = false)
    private Short defaultDueDayForNewStructures = 10;
}
