-- public.address definition

-- Drop table

-- DROP TABLE public.address;

CREATE TABLE public.address (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address_line text NULL,
	city varchar(255) NULL,
	country varchar(255) NULL,
	state varchar(255) NULL,
	zip_code varchar(255) NULL,
	CONSTRAINT address_pkey PRIMARY KEY (id)
);


-- public.branch definition

-- Drop table

-- DROP TABLE public.branch;

CREATE TABLE public.branch (
	branch_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	branch_code varchar(255) NOT NULL,
	branch_name varchar(255) NOT NULL,
	is_active bool NULL,
	"location" varchar(255) NULL,
	CONSTRAINT branch_pkey PRIMARY KEY (branch_id),
	CONSTRAINT ukisfsopa9nxf3amcuj963nb41g UNIQUE (branch_name),
	CONSTRAINT ukspmmcodjifhtymlws7w5fttgl UNIQUE (branch_code)
);


-- public."class" definition

-- Drop table

-- DROP TABLE public."class";

CREATE TABLE public."class" (
	class_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	class_name varchar(255) NOT NULL,
	CONSTRAINT class_pkey PRIMARY KEY (class_id)
);


-- public.department definition

-- Drop table

-- DROP TABLE public.department;

CREATE TABLE public.department (
	department_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	department_code varchar(255) NOT NULL,
	department_name varchar(255) NOT NULL,
	description varchar(500) NULL,
	is_active bool NULL,
	CONSTRAINT department_pkey PRIMARY KEY (department_id),
	CONSTRAINT ukf5np34wnxt905fwmrs6133l28 UNIQUE (department_name),
	CONSTRAINT uktc0vggvvuqc22trtdy0dmrahh UNIQUE (department_code)
);


-- public.menu_master definition

-- Drop table

-- DROP TABLE public.menu_master;

CREATE TABLE public.menu_master (
	menu_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	description text NULL,
	icon varchar(55) NULL,
	is_active bool NULL,
	menu_code varchar(255) NULL,
	menu_order int4 NULL,
	"name" varchar(50) NOT NULL,
	url varchar(55) NULL,
	CONSTRAINT menu_master_pkey PRIMARY KEY (menu_id)
);


-- public.privilege_master definition

-- Drop table

-- DROP TABLE public.privilege_master;

CREATE TABLE public.privilege_master (
	privilege_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	privilege_name varchar(50) NOT NULL,
	CONSTRAINT privilege_master_pkey PRIMARY KEY (privilege_id),
	CONSTRAINT uko82uvx84yphm3y1r3rf9a6ab7 UNIQUE (privilege_name)
);


-- public.role_master definition

-- Drop table

-- DROP TABLE public.role_master;

CREATE TABLE public.role_master (
	role_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	description text NULL,
	is_active bool NULL,
	organization_id int8 NULL,
	role_code varchar(50) NULL,
	role_name varchar(50) NOT NULL,
	role_type varchar(30) NULL,
	CONSTRAINT role_master_pkey PRIMARY KEY (role_id),
	CONSTRAINT role_master_role_type_check CHECK (((role_type)::text = ANY ((ARRAY['SCHOOL'::character varying, 'COLLEGE'::character varying, 'UNIVERSITY'::character varying, 'ADMIN'::character varying])::text[]))),
	CONSTRAINT ukermkbsp5njhawu0uk2bmj8lks UNIQUE (role_code)
);


-- public.schema_meta_data definition

-- Drop table

-- DROP TABLE public.schema_meta_data;

CREATE TABLE public.schema_meta_data (
	id varchar(50) NOT NULL,
	"password" varchar(255) NULL,
	schema_name varchar(255) NULL,
	url varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT schema_meta_data_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	address varchar(255) NULL,
	attempts int4 NULL,
	city varchar(255) NULL,
	email varchar(255) NOT NULL,
	first_name varchar(255) NOT NULL,
	is_2fa_enabled bool NULL,
	is_blocked bool NULL,
	is_first_time_login bool NULL,
	last_name varchar(255) NOT NULL,
	lock_date_time timestamp(6) NULL,
	max_device_allow int4 NULL,
	middle_name varchar(255) NULL,
	mobile_number int8 NOT NULL,
	"password" varchar(60) NOT NULL,
	remarks varchar(255) NULL,
	secret_operation varchar(255) NULL,
	state varchar(255) NULL,
	user_code varchar(255) NOT NULL,
	user_name varchar(255) NOT NULL,
	CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx UNIQUE (user_name),
	CONSTRAINT ukt4oh2dnaf9b4jc7qj8rxswgyh UNIQUE (user_code),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.guardian definition

-- Drop table

-- DROP TABLE public.guardian;

CREATE TABLE public.guardian (
	guardian_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address text NULL,
	created_at timestamp(6) NULL,
	email varchar(50) NULL,
	first_name varchar(50) NULL,
	last_name varchar(50) NULL,
	middle_name varchar(50) NULL,
	mobile_number int8 NOT NULL,
	relation varchar(10) NULL,
	updated_at timestamp(6) NULL,
	user_id int8 NULL,
	CONSTRAINT guardian_pkey PRIMARY KEY (guardian_id),
	CONSTRAINT ukdic46x6kqr2cqqhrps9a4b65e UNIQUE (user_id),
	CONSTRAINT fk78238bh00pipro62xntxayb9x FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.organisation definition

-- Drop table

-- DROP TABLE public.organisation;

CREATE TABLE public.organisation (
	org_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	brand_name varchar(255) NULL,
	city varchar(255) NULL,
	establishment_date date NULL,
	is_active bool NULL,
	is_group bool NULL,
	org_code varchar(50) NOT NULL,
	org_name varchar(255) NOT NULL,
	org_url varchar(255) NULL,
	state varchar(255) NULL,
	subscription_type varchar(50) NULL,
	"type" varchar(50) NULL,
	parent_org_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT organisation_pkey PRIMARY KEY (org_id),
	CONSTRAINT ukchd15mrfx7slue9vae2rvjs0i UNIQUE (org_code),
	CONSTRAINT fk7fe1cxfbwcb8f0ns4xvaniyao FOREIGN KEY (parent_org_id) REFERENCES public.organisation(org_id),
	CONSTRAINT fkdiyk5ra1jiihwhyoev7u9etp9 FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.owner_details definition

-- Drop table

-- DROP TABLE public.owner_details;

CREATE TABLE public.owner_details (
	owner_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	gender varchar(10) NULL,
	owner_code varchar(50) NULL,
	owner_email varchar(255) NULL,
	owner_mobile varchar(20) NULL,
	owner_name varchar(100) NULL,
	org_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT owner_details_pkey PRIMARY KEY (owner_id),
	CONSTRAINT uk4p1dvwn9adevvem5yfoh9clk6 UNIQUE (org_id),
	CONSTRAINT uk5vyl8wqq92b1khqo1s6chny27 UNIQUE (user_id),
	CONSTRAINT ukbbo3oa2cibch9s9t607tjtj73 UNIQUE (owner_code),
	CONSTRAINT fk5638gjc6jkwq0gj6adp1bak4i FOREIGN KEY (org_id) REFERENCES public.organisation(org_id),
	CONSTRAINT fkiuk30qky3ejwp35qeq3hbr4d8 FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.password_reset_token definition

-- Drop table

-- DROP TABLE public.password_reset_token;

CREATE TABLE public.password_reset_token (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	expiration_date timestamp(6) NOT NULL,
	"token" varchar(255) NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT password_reset_token_pkey PRIMARY KEY (id),
	CONSTRAINT ukg0guo4k8krgpwuagos61oc06j UNIQUE (token),
	CONSTRAINT fk83nsrttkwkb6ym0anu051mtxn FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.refresh_token definition

-- Drop table

-- DROP TABLE public.refresh_token;

CREATE TABLE public.refresh_token (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	expiry_date timestamptz(6) NOT NULL,
	"token" varchar(512) NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT refresh_token_pkey PRIMARY KEY (id),
	CONSTRAINT ukf95ixxe7pa48ryn1awmh2evt7 UNIQUE (user_id),
	CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token),
	CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public."section" definition

-- Drop table

-- DROP TABLE public."section";

CREATE TABLE public."section" (
	section_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	section_name varchar(255) NOT NULL,
	class_entity_class_id int8 NULL,
	CONSTRAINT section_pkey PRIMARY KEY (section_id),
	CONSTRAINT fkmp0d1954x86u7s6939a7iqk5d FOREIGN KEY (class_entity_class_id) REFERENCES public."class"(class_id)
);


-- public.staff definition

-- Drop table

-- DROP TABLE public.staff;

CREATE TABLE public.staff (
	staff_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	address varchar(500) NULL,
	city varchar(255) NULL,
	date_of_birth date NULL,
	email varchar(255) NOT NULL,
	first_name varchar(255) NULL,
	gender varchar(20) NULL,
	hire_date date NULL,
	is_active bool NULL,
	last_name varchar(255) NULL,
	middle_name varchar(255) NULL,
	mobile_number int8 NOT NULL,
	photo_url varchar(500) NULL,
	remarks text NULL,
	staff_code varchar(255) NOT NULL,
	state varchar(255) NULL,
	branch_id int8 NOT NULL,
	department_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT staff_pkey PRIMARY KEY (staff_id),
	CONSTRAINT uk9ovwaulv155suydr9xljxsgnj UNIQUE (mobile_number),
	CONSTRAINT ukpvctx4dbua9qh4p4s3gm3scrh UNIQUE (email),
	CONSTRAINT uktkv6oqgei31ht6h0jsoj61008 UNIQUE (staff_code),
	CONSTRAINT fk686rqn8cpu4ncey4odd8cw3hm FOREIGN KEY (department_id) REFERENCES public.department(department_id),
	CONSTRAINT fkc9xh37lh8sjk8m5hhp5bnq1ca FOREIGN KEY (branch_id) REFERENCES public.branch(branch_id),
	CONSTRAINT fkdlvw23ak3u9v9bomm8g12rtc0 FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.student definition

-- Drop table

-- DROP TABLE public.student;

CREATE TABLE public.student (
	student_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	age int8 NULL,
	date_of_birth date NULL,
	email varchar(50) NOT NULL,
	enrollment_date date NULL,
	first_name varchar(50) NULL,
	gender varchar(10) NULL,
	is_active bool NULL,
	is_same_address bool NULL,
	last_name varchar(50) NULL,
	middle_name varchar(50) NULL,
	mobile_number int8 NOT NULL,
	photo_url varchar(255) NULL,
	remarks text NULL,
	roll_number varchar(50) NULL,
	class_id int8 NULL,
	current_address_id int8 NULL,
	guardian_id int8 NOT NULL,
	permanent_address_id int8 NULL,
	section_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT student_pkey PRIMARY KEY (student_id),
	CONSTRAINT uk3ocykn0brvo25ctocwjnc6v5n UNIQUE (date_of_birth),
	CONSTRAINT ukbkix9btnoi1n917ll7bplkvg5 UNIQUE (user_id),
	CONSTRAINT ukfe0i52si7ybu0wjedj6motiim UNIQUE (email),
	CONSTRAINT uklveppkmt4yf9yyqby9xd4d8s9 UNIQUE (enrollment_date),
	CONSTRAINT ukng18h3c3bgj5caqbi2opf6uyp UNIQUE (is_same_address),
	CONSTRAINT uko1g1spw0ecyidv94ka2dk88wf UNIQUE (roll_number),
	CONSTRAINT ukrguwj66alc6nvyjtwdl6xcoq7 UNIQUE (permanent_address_id),
	CONSTRAINT ukt4917jp0sx54fbj9vh1b3susi UNIQUE (current_address_id),
	CONSTRAINT fkdwhkib64u47wc4yo4hk0cub90 FOREIGN KEY (class_id) REFERENCES public."class"(class_id),
	CONSTRAINT fke0jaefltp39n72oaynbquavtu FOREIGN KEY (permanent_address_id) REFERENCES public.address(id),
	CONSTRAINT fkhbvsrbyf0pkgo53royos2qk4k FOREIGN KEY (current_address_id) REFERENCES public.address(id),
	CONSTRAINT fkj1c0de75pterue04btw6w5mh8 FOREIGN KEY (section_id) REFERENCES public."section"(section_id),
	CONSTRAINT fkk0thg920a3xk3v59yjbsatw1l FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fkkktpamdaydbva4kxjcn17sbvk FOREIGN KEY (guardian_id) REFERENCES public.guardian(guardian_id)
);


-- public.sub_menu_master definition

-- Drop table

-- DROP TABLE public.sub_menu_master;

CREATE TABLE public.sub_menu_master (
	sub_menu_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	is_active bool NOT NULL,
	sub_menu_code varchar(50) NOT NULL,
	sub_menu_description text NULL,
	sub_menu_icon varchar(100) NULL,
	sub_menu_name varchar(100) NOT NULL,
	sub_menu_order int4 NULL,
	sub_menu_url varchar(200) NULL,
	menu_id int8 NOT NULL,
	CONSTRAINT sub_menu_master_pkey PRIMARY KEY (sub_menu_id),
	CONSTRAINT uk709rtwhykwrsyf2gft2au05w UNIQUE (sub_menu_code),
	CONSTRAINT fkb85x2ldxes2aawp2tm6l22agr FOREIGN KEY (menu_id) REFERENCES public.menu_master(menu_id)
);


-- public.submenu_privilege_mapping definition

-- Drop table

-- DROP TABLE public.submenu_privilege_mapping;

CREATE TABLE public.submenu_privilege_mapping (
	mapping_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	privilege_id int8 NOT NULL,
	sub_menu_id int8 NOT NULL,
	CONSTRAINT submenu_privilege_mapping_pkey PRIMARY KEY (mapping_id),
	CONSTRAINT fk7svjf9w09egt2fhat8cr7w4ix FOREIGN KEY (privilege_id) REFERENCES public.privilege_master(privilege_id),
	CONSTRAINT fkgw4uli0ql5yynwwdqtoercoel FOREIGN KEY (sub_menu_id) REFERENCES public.sub_menu_master(sub_menu_id)
);


-- public.user_roles definition

-- Drop table

-- DROP TABLE public.user_roles;

CREATE TABLE public.user_roles (
	user_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT fk2ptgru2sianmji5yk32p4kdfj FOREIGN KEY (role_id) REFERENCES public.role_master(role_id),
	CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.role_submenu_privilege_mapping definition

-- Drop table

-- DROP TABLE public.role_submenu_privilege_mapping;

CREATE TABLE public.role_submenu_privilege_mapping (
	mapping_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamp(6) NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp(6) NULL,
	privilege_id int8 NOT NULL,
	role_id int8 NOT NULL,
	sub_menu_id int8 NOT NULL,
	CONSTRAINT role_submenu_privilege_mapping_pkey PRIMARY KEY (mapping_id),
	CONSTRAINT fk7jqt3j378sy52a8geufpb8hpw FOREIGN KEY (role_id) REFERENCES public.role_master(role_id),
	CONSTRAINT fkb6vl70k1ulwfka5h5fejkv5u5 FOREIGN KEY (sub_menu_id) REFERENCES public.sub_menu_master(sub_menu_id),
	CONSTRAINT fkhj9xptnt4ge1mhhj5codj6cui FOREIGN KEY (privilege_id) REFERENCES public.privilege_master(privilege_id)
);