package com.thinkerscave.finance.service.impl;

import com.thinkerscave.audit.enums.AuditEventType;
import com.thinkerscave.audit.service.AuditWriteService;
import com.thinkerscave.finance.dto.request.GenerationRunRequest;
import com.thinkerscave.finance.dto.request.GenerationSettingsRequest;
import com.thinkerscave.finance.dto.request.ReminderSettingsRequest;
import com.thinkerscave.finance.dto.response.FinanceSettingsResponse;
import com.thinkerscave.finance.dto.response.PaymentMethodResponse;
import com.thinkerscave.finance.entity.FeeReminderRule;
import com.thinkerscave.finance.entity.FinanceConfiguration;
import com.thinkerscave.finance.repository.FeeReminderRuleRepository;
import com.thinkerscave.finance.repository.FinanceConfigurationRepository;
import com.thinkerscave.finance.security.FinanceAccessGuard;
import com.thinkerscave.finance.service.FeeGenerationService;
import com.thinkerscave.finance.service.FinanceSettingsService;
import com.thinkerscave.finance.service.PaymentMethodService;
import com.thinkerscave.shared.exceptions.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class FinanceSettingsServiceImpl implements FinanceSettingsService {

    private final FinanceAccessGuard accessGuard;
    private final FinanceConfigurationRepository configurationRepository;
    private final FeeReminderRuleRepository reminderRuleRepository;
    private final PaymentMethodService paymentMethodService;
    private final FeeGenerationService feeGenerationService;
    private final AuditWriteService auditWriteService;

    @Override
    public FinanceSettingsResponse get() {
        accessGuard.requireView(FinanceAccessGuard.RESOURCE_SETTINGS);
        // GET must NOT insert — read only; seed assumed present via migration
        FinanceConfiguration config = configurationRepository.findAll().stream().findFirst().orElse(null);
        List<FeeReminderRule> rules = reminderRuleRepository.findAllByOrderByFeeReminderRuleIdAsc();
        List<PaymentMethodResponse> methods = paymentMethodService.list(null);
        if (config == null && rules.isEmpty()) {
            return FinanceSettingsResponse.builder()
                    .autoGenerateDues(true)
                    .generationLeadDays(5)
                    .defaultDueDayForNewStructures((short) 10)
                    .reminderRules(List.of())
                    .paymentMethods(methods)
                    .build();
        }
        if (config == null) {
            throw new ResourceNotFoundException("Finance configuration not provisioned");
        }
        return toResponse(config, rules, methods);
    }

    @Override
    @Transactional
    public FinanceSettingsResponse updateGeneration(GenerationSettingsRequest request) {
        accessGuard.requireManage(FinanceAccessGuard.RESOURCE_SETTINGS);
        FinanceConfiguration config = configurationRepository.findAll().stream().findFirst()
                .orElseThrow(() -> new ResourceNotFoundException("Finance configuration not provisioned"));
        config.setAutoGenerateDues(request.getAutoGenerateDues());
        config.setGenerationLeadDays(request.getGenerationLeadDays());
        config.setDefaultDueDayForNewStructures(request.getDefaultDueDayForNewStructures());
        configurationRepository.save(config);
        auditWriteService.record(AuditEventType.CONFIG_CHANGE, "FINANCE_GENERATION_CONFIG", "FinanceConfiguration",
                String.valueOf(config.getFinanceConfigurationId()), "Updated generation settings");
        return get();
    }

    @Override
    @Transactional
    public FinanceSettingsResponse updateReminders(ReminderSettingsRequest request) {
        accessGuard.requireManage(FinanceAccessGuard.RESOURCE_SETTINGS);
        for (ReminderSettingsRequest.Rule ruleReq : request.getRules()) {
            FeeReminderRule rule = reminderRuleRepository.findByRuleKey(ruleReq.getRuleKey())
                    .orElseThrow(() -> new ResourceNotFoundException("Reminder rule not found: " + ruleReq.getRuleKey()));
            rule.setEnabled(ruleReq.getEnabled());
            rule.setOffsetDays(ruleReq.getOffsetDays());
            if (ruleReq.getChannelsCsv() != null && !ruleReq.getChannelsCsv().isBlank()) {
                rule.setChannelsCsv(ruleReq.getChannelsCsv());
            }
            reminderRuleRepository.save(rule);
        }
        auditWriteService.record(AuditEventType.CONFIG_CHANGE, "FINANCE_REMINDER_CONFIG", "FeeReminderRule",
                "ALL", "Updated reminder rules");
        return get();
    }

    @Override
    @Transactional
    public int runGeneration(GenerationRunRequest request) {
        accessGuard.requireManage(FinanceAccessGuard.RESOURCE_SETTINGS);
        return feeGenerationService.generate(request.getAcademicYearId(), request.getClassId());
    }

    private FinanceSettingsResponse toResponse(FinanceConfiguration config, List<FeeReminderRule> rules,
                                               List<PaymentMethodResponse> methods) {
        return FinanceSettingsResponse.builder()
                .autoGenerateDues(config.getAutoGenerateDues())
                .generationLeadDays(config.getGenerationLeadDays())
                .defaultDueDayForNewStructures(config.getDefaultDueDayForNewStructures())
                .reminderRules(rules.stream().map(r -> FinanceSettingsResponse.ReminderRuleResponse.builder()
                        .ruleKey(r.getRuleKey())
                        .enabled(r.getEnabled())
                        .offsetDays(r.getOffsetDays())
                        .channelsCsv(r.getChannelsCsv())
                        .build()).toList())
                .paymentMethods(methods)
                .build();
    }
}
