package com.thinkerscave.finance.scheduling;

import com.thinkerscave.academics.entity.AcademicYear;
import com.thinkerscave.academics.repository.AcademicYearRepository;
import com.thinkerscave.finance.entity.FinanceConfiguration;
import com.thinkerscave.finance.repository.FinanceConfigurationRepository;
import com.thinkerscave.finance.service.FeeGenerationService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

/**
 * Daily fee due generation across all completed tenant schemas.
 * Skips a tenant when autoGenerateDues is false or config is missing.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class FeeGenerationJob {

    private final FinanceTenantJobRunner tenantJobRunner;
    private final FeeGenerationService feeGenerationService;
    private final FinanceConfigurationRepository configurationRepository;
    private final AcademicYearRepository academicYearRepository;

    @Scheduled(cron = "${app.fees.generation.cron:0 15 2 * * *}", zone = "UTC")
    public void generateDues() {
        tenantJobRunner.forEachTenant("FeeGenerationJob", tenant -> {
            FinanceConfiguration config = configurationRepository.findAll().stream().findFirst().orElse(null);
            if (config == null || !Boolean.TRUE.equals(config.getAutoGenerateDues())) {
                log.debug("Fee generation skipped for {} (autoGenerateDues off or config missing)",
                        tenant.getSchemaName());
                return;
            }
            for (AcademicYear year : academicYearRepository.findAll()) {
                if (!Boolean.TRUE.equals(year.getActive())) {
                    continue;
                }
                try {
                    int created = feeGenerationService.generateSystem(year.getAcademicYearId(), null);
                    if (created > 0) {
                        log.info("Fee generation created {} periods for academic year {} in {}",
                                created, year.getName(), tenant.getSchemaName());
                    }
                } catch (Exception ex) {
                    log.warn("Fee generation failed for academic year {} in {}: {}",
                            year.getName(), tenant.getSchemaName(), ex.getMessage());
                }
            }
        });
    }
}
