package com.thinkerscave.finance.dto.response;

import com.thinkerscave.finance.enums.ReminderRuleKey;
import lombok.Builder;
import lombok.Data;

import java.util.List;

@Data
@Builder
public class FinanceSettingsResponse {
    private Boolean autoGenerateDues;
    private Integer generationLeadDays;
    private Short defaultDueDayForNewStructures;
    private List<ReminderRuleResponse> reminderRules;
    private List<PaymentMethodResponse> paymentMethods;

    @Data
    @Builder
    public static class ReminderRuleResponse {
        private ReminderRuleKey ruleKey;
        private Boolean enabled;
        private Integer offsetDays;
        private String channelsCsv;
    }
}
