package com.thinkerscave.academics.enums;

public enum TimetableConflictType {
    TEACHER_CONFLICT,
    CLASS_CONFLICT,
    SECTION_CONFLICT,
    ROOM_CONFLICT,
    RESOURCE_CONFLICT,
    TEACHER_AVAILABILITY_CONFLICT,
    ROOM_CAPACITY_CONFLICT,
    PERIOD_CAPACITY_CONFLICT,
    WORKLOAD_CONFLICT,
    SUBJECT_ALLOCATION_CONFLICT
}
